name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@v0.24.0
    with:
      image: 'ghcr.io/radiorabe/roundcubemail'
      name: roundcubemail
      display-name: Roundcube Mail
      tags: 'rabe roundcubemail'
      cosign-verify: false
      cosign-base-image-only: true
