name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@f49d301c653f9aa0d99bec7b7f18f2d789e93fa7 # v0.43.4
    with:
      image: 'ghcr.io/radiorabe/roundcubemail'
      name: roundcubemail
      display-name: Roundcube Mail
      tags: 'rabe roundcubemail'
      cosign-verify: false
      cosign-base-image-only: true
